---
- name: Send email notification on failure
  community.general.mail:
    host: "{{ host }}"
    port: "{{ port }}"
    username: "{{ username }}"
    password: "{{ password }}"
    from: "{{ from }}"
    to: "{{ to }}"
    subject: "{{ subject }}"
    body: "{{ body }}"
  # when: failed_hosts_list | length > 0 # Put this on the task
  delegate_to: localhost