---
- name: Send email notification on failure
  community.general.mail:
    host: "{{ host }}"
    port: "{{ port }}"
    username: "{{ username }}"
    password: "{{ password }}"
    from: "{{ sender }}"
    to: "{{ recipient_list }}"  # A list of email addresses
    subject: "{{ subject }}"
    body: "{{ body }}"
  delegate_to: localhost
  run_once: true
  ignore_errors: true